platform :ios, '13.0'

target 'SwiftSyft_Example' do
  pod 'SwiftSyft', :path => '../'

  # Not included until https://github.com/CocoaPods/CocoaPods/issues/9473 is resolved
#  target 'SwiftSyft_Tests' do
#    inherit! :search_paths
#  end
end
