name: Release to Cocoapods

on:
  release:
    types:
      - published

jobs:
  documentation:

    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    name: Create API documentation
    if: github.event_name == 'release' && !failure()

    steps:
      - uses: actions/checkout@v2

      - name: Install and run cocoapods
        run: |
          gem install cocoapods
          pod install

      - name: Install sourcedocs
        run: |
          brew install sourcedocs

      - name: Generated API documentation
        run: |
          sourcedocs generate -t --module-name=SwiftSyft -- -scheme SwiftSyft-Example -workspace SwiftSyft.xcworkspace

      - name: Commit changes in documentation
        uses: EndBug/add-and-commit@v4
        with:
          message: "Updated documentation."
          author_name: "github_workflow"
          add: "Documentation/*"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  publish:
    needs: documentation
    runs-on: macos-latest
    env: 
      DEVELOPER_DIR: /Applications/Xcode_12.2.app/Contents/Developer
    name: Publish this version to Cocoapods
    if: github.event_name == 'release' && !failure()

    steps:
      - uses: actions/checkout@v2

      - name: Install and run cocoapods
        run: |
          gem install cocoapods
          pod install

      - name: Publish to cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          set -eo pipefail
          pod lib lint --allow-warnings
          pod trunk push --allow-warnings





